-- Select the database
use atthelocal;

-- Create table for users
CREATE TABLE Users (
    id VARCHAR(255) PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(20) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    joinDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    primaryLocation VARCHAR(255) DEFAULT NULL,
    profileSettings JSON DEFAULT NULL
);